format-version = 1

autostart = true

[[sessions]]
id = 'reviewer'
name = 'Reviewer General'
directory = '/home/me/src/WORKTREES/agentmux/reviewer'
coder = 'opencode'
policy = 'coordinator'

[[sessions]]
id = 'agents'
name = 'Agents Engineer'
directory = '/home/me/src/WORKTREES/agentmux/agents-aux'
coder = 'opencode'

[[sessions]]
id = 'api'
name = 'Extensions Engineer'
directory = '/home/me/src/WORKTREES/agentmux/api-aux'
coder = 'opencode'

[[sessions]]
id = 'backend'
name = 'Backend Engineer'
directory = '/home/me/src/WORKTREES/agentmux/backend-aux'
coder = 'opencode'

[[sessions]]
id = 'frontend'
name = 'Frontend Engineer'
directory = '/home/me/src/WORKTREES/agentmux/frontend-aux'
coder = 'opencode'

[[sessions]]
id = 'qa-partner'
name = 'QA Partner'
directory = '/home/me/src/WORKTREES/agentmux/qa-partner'
coder = 'opencode-acp'
policy = 'coordinator'
