format-version = 1

autostart = true

[[sessions]]
id = 'coordinator'
name = 'Coordinator'
directory = '/home/me/src/agentmux'
coder = 'opencode'
policy = 'coordinator'

[[sessions]]
id = 'advisor'
name = 'Advisor'
directory = '/home/me/src/WORKTREES/agentmux/advisor'
coder = 'opencode'
# policy = 'coordinator'

[[sessions]]
id = 'reviewer'
name = 'Reviewer General'
directory = '/home/me/src/WORKTREES/agentmux/reviewer'
coder = 'opencode'

[[sessions]]
id = 'agents'
name = 'Agents Engineer'
directory = '/home/me/src/WORKTREES/agentmux/agents'
coder = 'opencode'

[[sessions]]
id = 'backend'
name = 'Backend Engineer'
directory = '/home/me/src/WORKTREES/agentmux/backend'
coder = 'opencode'

[[sessions]]
id = 'frontend'
name = 'Frontend Engineer'
directory = '/home/me/src/WORKTREES/agentmux/frontend'
coder = 'opencode'

[[sessions]]
id = 'acp'
name = 'ACP Specialist'
directory = '/home/me/src/WORKTREES/agentmux/acp'
coder = 'opencode'

[[sessions]]
id = 'pty'
name = 'Pty Specialist'
directory = '/home/me/src/WORKTREES/agentmux/pty'
coder = 'opencode'
