format-version = 1

autostart = false

[[sessions]]
id = 'coordinator'
name = 'Coordinator'
directory = '/home/me/src/home'
coder = 'opencode'

[[sessions]]
id = 'advisor'
name = 'Advisor'
directory = '/home/me/src/WORKTREES/home/advisor'
coder = 'opencode'

[[sessions]]
id = 'reviewer'
name = 'Reviewer General'
directory = '/home/me/src/WORKTREES/home/infras-reviewer'
coder = 'opencode'

[[sessions]]
id = 'agents'
name = 'Agents Owner'
directory = '/home/me/src/agents-common'
coder = 'opencode'

[[sessions]]
id = 'cistella'
name = 'Cistella Owner'
directory = '/home/me/src/cistella'
coder = 'opencode'

[[sessions]]
id = 'cistella-qa'
name = 'Cistella QA Partner'
directory = '/home/me/src/CLONES/cistella/qa'
coder = 'cistella-opencode'

[[sessions]]
id = 'dispositor'
name = 'Dispositor Owner'
directory = '/home/me/src/dispositor'
coder = 'opencode'

[[sessions]]
id = 'mysite'
name = 'Weblog Owner'
directory = '/home/me/src/mysite'
coder = 'opencode'

[[sessions]]
id = 'pc-setup'
name = 'PC Setup Owner'
directory = '/home/me/src/pc-setup'
coder = 'opencode'

[[sessions]]
id = 'praetor'
name = 'Praetor Owner'
directory = '/home/me/src/praetor'
coder = 'opencode'

[[sessions]]
id = 'repositor'
name = 'Repositories Owner'
directory = '/home/me/src/gh-repositor'
coder = 'opencode'
