format-version = 1

autostart = false

# [[sessions]]
# id = 'scribbles'
# name = 'Coordinator'
# directory = '/home/me/src/lm-scribbles'
# coder = 'opencode'

[[sessions]]
id = 'home'
name = 'Coordinator'
directory = '/home/me/src/home'
coder = 'opencode'

[[sessions]]
id = 'home-deput'  # Yes, it's a Lowes-y pun.
name = 'Deputy Coordinator'
directory = '/home/me/src/WORKTREES/home/deputy'
coder = 'opencode'

[[sessions]]
id = 'agents'
name = 'Agents Owner'
directory = '/home/me/src/agents-common'
coder = 'opencode'

[[sessions]]
id = 'agents-xo'
name = 'Agents XO'
directory = '/home/me/src/WORKTREES/agents-common/xo'
coder = 'opencode'

[[sessions]]
id = 'copiertv'
name = 'Copier TV Owner'
directory = '/home/me/src/copier-template-validator'
coder = 'opencode'

[[sessions]]
id = 'mysite'
name = 'Weblog Owner'
directory = '/home/me/src/mysite'
coder = 'opencode'

[[sessions]]
id = 'nb-mcp'
name = 'Notebook MCP Owner'
directory = '/home/me/src/nb-mcp-server'
coder = 'opencode'

[[sessions]]
id = 'nb-mcp-qa'
name = 'Notebook MCP QA'
directory = '/home/me/src/WORKTREES/nb-mcp-server/qa'
coder = 'opencode'

[[sessions]]
id = 'nb-mcp-xo'
name = 'Notebook MCP XO'
directory = '/home/me/src/WORKTREES/nb-mcp-server/xo'
coder = 'opencode'

[[sessions]]
id = 'pc-setup'
name = 'PC Setup Owner'
directory = '/home/me/src/pc-setup'
coder = 'opencode'

[[sessions]]
id = 'python'
name = 'Python Owner'
directory = '/home/me/src/python-project-common'
coder = 'opencode'

[[sessions]]
id = 'python-xo'
name = 'Python XO'
directory = '/home/me/src/WORKTREES/python-project-common/xo'
coder = 'opencode'

[[sessions]]
id = 'repositor'
name = 'Repositories Owner'
directory = '/home/me/src/gh-repositor'
coder = 'opencode'
