format-version = 1

autostart = false

[[sessions]]
id = 'reviewer'
name = 'Reviewer General'
directory = '/home/me/src/WORKTREES/home/pyf-reviewer'
coder = 'opencode'

[[sessions]]
id = 'template'
name = 'Template Owner'
directory = '/home/me/src/python-project-common'
coder = 'opencode'

[[sessions]]
id = 'absence'
name = 'Absence Owner'
directory = '/home/me/src/python-absence'
coder = 'opencode'

[[sessions]]
id = 'accretive'
name = 'Accretive Owner'
directory = '/home/me/src/python-accretive'
coder = 'opencode'

[[sessions]]
id = 'appcore'
name = 'Appcore Owner'
directory = '/home/me/src/python-appcore'
coder = 'opencode'

[[sessions]]
id = 'classcore'
name = 'Classcore Owner'
directory = '/home/me/src/python-classcore'
coder = 'opencode'

[[sessions]]
id = 'dynadoc'
name = 'Dynadoc Owner'
directory = '/home/me/src/python-dynadoc'
coder = 'opencode'

[[sessions]]
id = 'falsifier'
name = 'Falsifier Owner'
directory = '/home/me/src/python-falsifier'
coder = 'opencode'

[[sessions]]
id = 'frigid'
name = 'Frigid Owner'
directory = '/home/me/src/python-frigid'
coder = 'opencode'

[[sessions]]
id = 'ictr'
name = 'Ictr Owner'
directory = '/home/me/src/python-ictr'
coder = 'opencode'

[[sessions]]
id = 'scent'
name = 'Scent Owner'
directory = '/home/me/src/python-scent'
coder = 'opencode'
