#!/usr/bin/env bash

set -eu -o pipefail

curl -fsSL https://claude.ai/install.sh | bash
npm install --global @openai/codex
npm install --global opencode-ai@latest

npm install --global difit
npm install --global @fission-ai/openspec@latest

# npm install --global @anthropic-ai/claude-code
# npm install --global @google/gemini-cli
